use pingchecker;

CREATE TABLE hosts(
	host VARCHAR(50) NOT NULL,
	description VARCHAR(50),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(host)
);

CREATE TABLE pings(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  host VARCHAR(50) NOT NULL REFERENCES hosts(host),
  ip VARCHAR(15),
  size SMALLINT,
  time_ms FLOAT(6,2),
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE downs(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  host VARCHAR(50) NOT NULL REFERENCES hosts(host),
  ip VARCHAR(15),
  last_down TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);